//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversityProfUnit {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UniversityProfUnit.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الدرجه الاكاديميه مستخدمة لا يمكن الحذف.
        /// </summary>
        internal static string AcademicDegreeCanNotDeleteIsUsed {
            get {
                return ResourceManager.GetString("AcademicDegreeCanNotDeleteIsUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الدرجه الاكاديميه غير موجودة.
        /// </summary>
        internal static string AcademicDegreeNotFound {
            get {
                return ResourceManager.GetString("AcademicDegreeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الدورات يجب ان تكوم علي الاقل ثلاثة.
        /// </summary>
        internal static string CourseListMustBeAtLeastThree {
            get {
                return ResourceManager.GetString("CourseListMustBeAtLeastThree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم الكورس مطلوب.
        /// </summary>
        internal static string CourseNameRequired {
            get {
                return ResourceManager.GetString("CourseNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوظيف الحالية مطلوبة.
        /// </summary>
        internal static string CurrentJopRequired {
            get {
                return ResourceManager.GetString("CurrentJopRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قناة الاتصال مستخدمة لا يمكن الحذف.
        /// </summary>
        internal static string DiscoveryChannelCanNotDeleteIsUsed {
            get {
                return ResourceManager.GetString("DiscoveryChannelCanNotDeleteIsUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قناة الاتصال غير موجودة.
        /// </summary>
        internal static string DiscoveryChannelNotFound {
            get {
                return ResourceManager.GetString("DiscoveryChannelNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الهاتف مكرر.
        /// </summary>
        internal static string DublicatedPhoneNumber {
            get {
                return ResourceManager.GetString("DublicatedPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الايميل مكرر.
        /// </summary>
        internal static string DuplicatedEmail {
            get {
                return ResourceManager.GetString("DuplicatedEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الايميل مطلوب.
        /// </summary>
        internal static string EmailRequired {
            get {
                return ResourceManager.GetString("EmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جهة العمل مطلوبة.
        /// </summary>
        internal static string EmployerIsRequired {
            get {
                return ResourceManager.GetString("EmployerIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الخبرات يجب ان تكون علي الاقل ثلاثة.
        /// </summary>
        internal static string ExperienceListMustBeAtLeastThree {
            get {
                return ResourceManager.GetString("ExperienceListMustBeAtLeastThree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم الاول مطلوب.
        /// </summary>
        internal static string FirstNameRequired {
            get {
                return ResourceManager.GetString("FirstNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الجنس مستخدم لا يمكن الحذف.
        /// </summary>
        internal static string GenderCanNotDeleteIsUsed {
            get {
                return ResourceManager.GetString("GenderCanNotDeleteIsUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الجنس غير موجود.
        /// </summary>
        internal static string GenderNotFound {
            get {
                return ResourceManager.GetString("GenderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ادخل التقييمات الاساسيه.
        /// </summary>
        internal static string InsertKPIMainCategory {
            get {
                return ResourceManager.GetString("InsertKPIMainCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ادخل التقييمات الفرعية.
        /// </summary>
        internal static string InsertKPISubCategory {
            get {
                return ResourceManager.GetString("InsertKPISubCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التاريخ غير صحيح.
        /// </summary>
        internal static string InvalidDate {
            get {
                return ResourceManager.GetString("InvalidDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم الوظيفة مطلوب.
        /// </summary>
        internal static string JopNameIsRequired {
            get {
                return ResourceManager.GetString("JopNameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوظيف الاساسية مطلوبة.
        /// </summary>
        internal static string MainJobRequired {
            get {
                return ResourceManager.GetString("MainJobRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم مطلوب.
        /// </summary>
        internal static string NameIsRequired {
            get {
                return ResourceManager.GetString("NameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الهاتف مطلوب.
        /// </summary>
        internal static string PhoneNumberRequired {
            get {
                return ResourceManager.GetString("PhoneNumberRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مختصر المنصب مطلوب.
        /// </summary>
        internal static string PositionAbbreviationRequired {
            get {
                return ResourceManager.GetString("PositionAbbreviationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الملف غير موجود.
        /// </summary>
        internal static string ProfileNotFound {
            get {
                return ResourceManager.GetString("ProfileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم الثاني مطلوب.
        /// </summary>
        internal static string SecondNameRequired {
            get {
                return ResourceManager.GetString("SecondNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التخصص مستخدم لا يمكن الحذف.
        /// </summary>
        internal static string SpecialtyCanNotDeleteIsUsed {
            get {
                return ResourceManager.GetString("SpecialtyCanNotDeleteIsUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التخصص مطلوب.
        /// </summary>
        internal static string SpecialtyIsRequired {
            get {
                return ResourceManager.GetString("SpecialtyIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التخصص غير موجود.
        /// </summary>
        internal static string SpecialtyNotFound {
            get {
                return ResourceManager.GetString("SpecialtyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اجمالي الاوزان يجب ان يكون 100.
        /// </summary>
        internal static string SumOfWehightMustBeOneHundered {
            get {
                return ResourceManager.GetString("SumOfWehightMustBeOneHundered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم الجامعة مطلوب.
        /// </summary>
        internal static string UniversityIsRequired {
            get {
                return ResourceManager.GetString("UniversityIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الهاتف غير صحيح.
        /// </summary>
        internal static string WrongPhoneNumber {
            get {
                return ResourceManager.GetString("WrongPhoneNumber", resourceCulture);
            }
        }
    }
}
