// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CORE.DAL
{
    public partial class City
    {
        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(200)]
        public string ArabicName { get; set; }
        [StringLength(200)]
        public string EnglishName { get; set; }
        public int CountryId { get; set; }

        
        public virtual Country Country { get; set; }
    }
}