// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CORE.DAL
{
    [Index(nameof(KPICategoryId), Name = "IX_KPI_KPICategoryId")]
    public partial class KPI
    {
        public KPI()
        {
            SupKPI = new HashSet<SupKPI>();
        }

        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(200)]
        public string Name { get; set; }
        public int Wehight { get; set; }
        public int KPICategoryId { get; set; }
        public bool? IsDeleted { get; set; }

        [ForeignKey(nameof(KPICategoryId))]
        [InverseProperty("KPI")]
        public virtual KPICategory KPICategory { get; set; }
        //[InverseProperty("KPI")]
        //public virtual ICollection<ProfileEvaluation> ProfileEvaluation { get; set; }
        [InverseProperty("KPI")]
        public virtual ICollection<SupKPI> SupKPI { get; set; }
    }
}