// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CORE.DAL
{
    public partial class KPICategory
    {
        public KPICategory()
        {
            KPI = new HashSet<KPI>();
            //ProfileEvaluation = new HashSet<ProfileEvaluation>();
            SupKPI = new HashSet<SupKPI>();
        }

        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(200)]
        public string Name { get; set; }
        public int Wehight { get; set; }

        [InverseProperty("KPICategory")]
        public virtual ICollection<KPI> KPI { get; set; }
        //[InverseProperty("KPICategory")]
        //public virtual ICollection<ProfileEvaluation> ProfileEvaluation { get; set; }
        [InverseProperty("KPICategory")]
        public virtual ICollection<SupKPI> SupKPI { get; set; }
    }
}