// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CORE.DAL
{
    [Index(nameof(Email), Name = "AK_Profile_Email", IsUnique = true)]
    [Index(nameof(PhoneNumber), Name = "AK_Profile_PhoneNumber", IsUnique = true)]
    [Index(nameof(DiscoveryChannelId), Name = "IX_Profile_DiscoveryChannelId")]
    [Index(nameof(GenderId), Name = "IX_Profile_GenderId")]
    [Index(nameof(PositionAbbreviationId), Name = "IX_Profile_PositionAbbreviationId")]
    [Index(nameof(SpecialtyId), Name = "IX_Profile_SpecialtyId")]
    public partial class profile
    {
        public profile()
        {
            ProfileAcademicDegree = new HashSet<ProfileAcademicDegree>();
            ProfileAwards = new HashSet<ProfileAwards>();
            ProfileCourses = new HashSet<ProfileCourses>();
            ProfileEvaluation = new HashSet<ProfileEvaluation>();
            ProfileExperiences = new HashSet<ProfileExperiences>();
            ProfileScientificResearch = new HashSet<ProfileScientificResearch>();
        }

        [Key]
        public int Id { get; set; }
       
        [StringLength(10)]
        public string Serial { get; set; }
        [Required]
        public string Name { get; set; }
        [Required]
        [StringLength(200)]
        public string Email { get; set; }
        [Required]
        [StringLength(12)]
        public string PhoneNumber { get; set; }
        public int SpecialtyId { get; set; }
        public int PositionAbbreviationId { get; set; }
        [Required]
        [StringLength(200)]
        public string CurrentJop { get; set; }
        [Required]
        [StringLength(200)]
        public string MainJob { get; set; }
        public int GenderId { get; set; }
        public int EmployerId { get; set; }
        
        public int? DiscoveryChannelId { get; set; }
        [StringLength(500)]
        public string Description { get; set; }
        public bool ProfileState { get; set; }
        public string ProfilePicturePath { get; set; }
        public string CVPath { get; set; }
        public int? AcademicRankId { get; set; }

        [ForeignKey(nameof(AcademicRankId))]
        public virtual AcademicRank AcademicRank { get; set; }
        [ForeignKey(nameof(DiscoveryChannelId))]
        public virtual DiscoveryChannels DiscoveryChannel { get; set; }
        [ForeignKey(nameof(GenderId))]
        public virtual Gender Gender { get; set; }
       
        [ForeignKey(nameof(EmployerId))]
        public virtual University Employer { get; set; }

        [ForeignKey(nameof(PositionAbbreviationId))]
        public virtual PositionAbbreviation PositionAbbreviation { get; set; }
        [ForeignKey(nameof(SpecialtyId))]
        public virtual Specialty Specialty { get; set; }
       
        [InverseProperty("Profile")]
        public virtual ICollection<ProfileAcademicDegree> ProfileAcademicDegree { get; set; }
        [InverseProperty("Profile")]
        public virtual ICollection<ProfileAwards> ProfileAwards { get; set; }
        [InverseProperty("Profile")]
        public virtual ICollection<ProfileCourses> ProfileCourses { get; set; }
        [InverseProperty("Pofile")]
        public virtual ICollection<ProfileEvaluation> ProfileEvaluation { get; set; }
        [InverseProperty("Profile")]
        public virtual ICollection<ProfileExperiences> ProfileExperiences { get; set; }
        [InverseProperty("Profile")]
        public virtual ICollection<ProfileScientificResearch> ProfileScientificResearch { get; set; }
    }
}