// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CORE.DAL
{
    [Index(nameof(ProfileId), Name = "IX_ProfileExperiences_ProfileId")]
    public partial class ProfileExperiences
    {
        [Key]
        public int Id { get; set; }
        public int ProfileId { get; set; }
        [Required]
        [StringLength(200)]
        public string JopName { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime FromDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ToDate { get; set; }
        [Required]
        [StringLength(500)]
        public string Description { get; set; }
        public int SpecialityRelationId { get; set; }
        public int EmployerId { get; set; }

        [ForeignKey(nameof(ProfileId))]
        [InverseProperty(nameof(profile.ProfileExperiences))]
        public virtual profile Profile { get; set; }
        public virtual ExperienceSpecialityRelation SpecialityRelation { get; set; }
        public virtual University Employer { get; set; }
    }
}