// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CORE.DAL
{
    [Index(nameof(AcademicDegreeId), Name = "IX_ProfileAcademicDegree_AcademicDegreeId")]
    [Index(nameof(ProfileId), Name = "IX_ProfileAcademicDegree_ProfileId")]
    public partial class ProfileAcademicDegree
    {
        [Key]
        public int Id { get; set; }
        public int ProfileId { get; set; }
        public int AcademicDegreeId { get; set; }
        public int SpecialtyId { get; set; }
        public int UniversityId { get; set; }
        [Column(TypeName = "date")]
        public DateTime? DegreeStartDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DegreeEndDate { get; set; }
       // public int? SecondSpecialtyId { get; set; }
      //  public string StudentActivity { get; set; }
        public string SupSpecialty { get; set; }

        [ForeignKey(nameof(AcademicDegreeId))]
        //[InverseProperty("ProfileAcademicDegree")]
        public virtual AcademicDegree AcademicDegree { get; set; }
        [ForeignKey(nameof(ProfileId))]
        [InverseProperty(nameof(profile.ProfileAcademicDegree))]
        public virtual profile Profile { get; set; }
        //[ForeignKey(nameof(SecondSpecialtyId))]
        //[InverseProperty("ProfileAcademicDegreeSecondSpecialty")]
        //public virtual Specialty SecondSpecialty { get; set; }
        [ForeignKey(nameof(SpecialtyId))]
        //[InverseProperty("ProfileAcademicDegreeSpecialty")]
        public virtual Specialty Specialty { get; set; }
        //[ForeignKey(nameof(UniversityId))]
        //[InverseProperty("ProfileAcademicDegree")]
        public virtual University University { get; set; }
    }
}