// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CORE.DAL
{
    [Index(nameof(KPICategoryId), Name = "IX_ProfileEvaluation_KPICategoryId")]
    [Index(nameof(KPIId), Name = "IX_ProfileEvaluation_KPIId")]
    [Index(nameof(PofileId), Name = "IX_ProfileEvaluation_PofileId")]
    [Index(nameof(SupKPIId), Name = "IX_ProfileEvaluation_SupKPIId")]
    public partial class ProfileEvaluation
    {
        [Key]
        public int Id { get; set; }
        public int PofileId { get; set; }
        public int KPICategoryId { get; set; }
        public int KPIId { get; set; }
        public int KPIDegree { get; set; }
        public int SupKPIId { get; set; }
        public int SupKPIDegree { get; set; }
        public int Grade { get; set; }
        public string Notes { get; set; }

        [ForeignKey(nameof(KPIId))]
        public virtual KPI KPI { get; set; }
        [ForeignKey(nameof(KPICategoryId))]
        public virtual KPICategory KPICategory { get; set; }
        [ForeignKey(nameof(PofileId))]
        [InverseProperty(nameof(profile.ProfileEvaluation))]
        public virtual profile Pofile { get; set; }
        [ForeignKey(nameof(SupKPIId))]
        public virtual SupKPI SupKPI { get; set; }
    }
}