// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CORE.DAL
{
    public partial class ProfileAwards
    {
        [Key]
        public int Id { get; set; }
        public int ProfileId { get; set; }
        [Required]
        public string AwardName { get; set; }
        public string Donor { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? AwardDate { get; set; }
        public int? AwardValue { get; set; }

        [ForeignKey(nameof(ProfileId))]
        [InverseProperty(nameof(profile.ProfileAwards))]
        public virtual profile Profile { get; set; }
    }
}