// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CORE.DAL
{
    [Index(nameof(ProfileId), Name = "IX_ProfileCourses_ProfileId")]
    public partial class ProfileCourses
    {
        [Key]
        public int Id { get; set; }
        public int ProfileId { get; set; }
        [Required]
        [StringLength(200)]
        public string CourseName { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime FromDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime ToDate { get; set; }
        [Required]
        [StringLength(500)]
        public string Description { get; set; }
        [Required]
        [StringLength(200)]
        public string Donor { get; set; }
        public int CertificateTypeId { get; set; }
        public int CityId { get; set; }

        //[ForeignKey(nameof(CertificateTypeId))]
        //[InverseProperty("ProfileCourses")]
        public virtual CertificateType CertificateType { get; set; }
        [ForeignKey(nameof(ProfileId))]
        [InverseProperty(nameof(profile.ProfileCourses))]
        public virtual profile Profile { get; set; }
        public virtual City City { get; set; }
    }
}