// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CORE.DAL
{
    public partial class ProfileScientificResearch
    {
        public ProfileScientificResearch()
        {
        }

        [Key]
        public int Id { get; set; }
        public int ProfileId { get; set; }
        [Required]
        public string ResearchTitle { get; set; }
        [Required]
        [StringLength(200)]
        public string Journal { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime PublishingDate { get; set; }
        [StringLength(200)]
        public string JournalImpactFactor { get; set; }

        [ForeignKey(nameof(ProfileId))]
        [InverseProperty(nameof(profile.ProfileScientificResearch))]
        public virtual profile Profile { get; set; }
        public string ParticepantsNames { get; set; }
         }
}