// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CORE.DAL
{
    [Index(nameof(KPICategoryId), Name = "IX_SupKPI_KPICategoryId")]
    [Index(nameof(KPIId), Name = "IX_SupKPI_KPIId")]
    public partial class SupKPI
    {
        public SupKPI()
        {
        }

        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(200)]
        public string Name { get; set; }
        public int Wehight { get; set; }
        public int KPIId { get; set; }
        public int KPICategoryId { get; set; }

        [ForeignKey(nameof(KPIId))]
        [InverseProperty("SupKPI")]
        public virtual KPI KPI { get; set; }
        [ForeignKey(nameof(KPICategoryId))]
        [InverseProperty("SupKPI")]
        public virtual KPICategory KPICategory { get; set; }
        
    }
}