// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CORE.DAL
{
    public partial class University
    {
        public University()
        {
        }

        [Key]
        public int Id { get; set; }
        [Required]
        public string Name { get; set; }
        public int? CityId { get; set; }
        public virtual City City { get; set; }

    }
}