// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using CORE.DAL;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using CORE.Identity;

#nullable disable

namespace CORE
{
    public partial class ApplicationDBContext : IdentityDbContext<ApplicationUser>
    {
        public ApplicationDBContext()
        {
        }

        public ApplicationDBContext(DbContextOptions<ApplicationDBContext> options)
            : base(options)
        {
        }

        public virtual DbSet<AcademicDegree> AcademicDegree { get; set; }
        public virtual DbSet<AcademicRank> AcademicRank { get; set; }
       
        public virtual DbSet<ApplicationUser> ApplicationUsers { get; set; }
        public virtual DbSet<ApplicationRole> ApplicationRoles { get; set; }
        public virtual DbSet<CertificateType> CertificateType { get; set; }
        public virtual DbSet<City> City { get; set; }
        public virtual DbSet<Country> Country { get; set; }
        public virtual DbSet<DiscoveryChannels> DiscoveryChannels { get; set; }
        public virtual DbSet<ExperienceSpecialityRelation> ExperienceSpecialityRelation { get; set; }
        public virtual DbSet<Gender> Gender { get; set; }
        public virtual DbSet<Grade> Grade { get; set; }
        public virtual DbSet<KPI> KPI { get; set; }
        public virtual DbSet<KPICategory> KPICategory { get; set; }
        public virtual DbSet<PositionAbbreviation> PositionAbbreviation { get; set; }
        public virtual DbSet<ProfileAcademicDegree> ProfileAcademicDegree { get; set; }
        public virtual DbSet<ProfileAwards> ProfileAwards { get; set; }
        public virtual DbSet<ProfileCourses> ProfileCourses { get; set; }
        public virtual DbSet<ProfileEvaluation> ProfileEvaluation { get; set; }
        public virtual DbSet<ProfileExperiences> ProfileExperiences { get; set; }
        public virtual DbSet<ProfileScientificResearch> ProfileScientificResearch { get; set; }
        public virtual DbSet<ScientificResearchParticipant> ScientificResearchParticipant { get; set; }
        public virtual DbSet<Specialty> Specialty { get; set; }
        public virtual DbSet<SupKPI> SupKPI { get; set; }
        public virtual DbSet<University> University { get; set; }
        public virtual DbSet<profile> profile { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
                optionsBuilder.UseSqlServer("Data Source=.;Initial Catalog=UniversityProfUnit;Integrated Security=True");
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);
        //    modelBuilder.Entity<AspNetUserLogins>()
        //.HasKey(p => new { p.LoginProvider, p.ProviderKey });

        //    modelBuilder.Entity<AspNetUserRoles>()
        //.HasKey(p => new { p.UserId, p.RoleId });

        //    modelBuilder.Entity<AspNetUserTokens>()
        //.HasKey(p => new { p.UserId, p.LoginProvider });
        }

    }
}